package session

import (
	"regexp"
	"strings"
	"testing"
)

// The default patterns must catch the trailers/footers real tools emit and
// leave human content alone. Compiled with Go's regexp here (RE2 accepts the
// same ERE subset grep -E uses for these patterns), matched per line like the
// hook's `grep -Ev -f` does.
func TestDefaultAttributionPatterns(t *testing.T) {
	res := make([]*regexp.Regexp, 0, len(DefaultAttributionPatterns))
	for _, p := range DefaultAttributionPatterns {
		re, err := regexp.Compile(p)
		if err != nil {
			t.Fatalf("default pattern %q does not compile: %v", p, err)
		}
		res = append(res, re)
	}
	matchAny := func(line string) bool {
		for _, re := range res {
			if re.MatchString(line) {
				return true
			}
		}
		return false
	}

	stripped := []string{
		"Co-Authored-By: Claude <noreply@anthropic.com>",
		"Co-authored-by: Claude Opus <noreply@anthropic.com>",
		"Co-Authored-By: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>",
		"Co-authored-by: aider (gpt-4o) <noreply@aider.chat>",
		"Co-Authored-By: Codex <codex@openai.com>",
		"Co-Authored-By: Cursor Agent <cursoragent@cursor.com>",
		"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
		"Generated with Claude Code",
		"Generated by Copilot",
		"  Co-Authored-By: Claude <noreply@anthropic.com>",
		"Assisted-by: Gemini",
	}
	for _, line := range stripped {
		if !matchAny(line) {
			t.Errorf("default patterns should strip %q", line)
		}
	}

	kept := []string{
		"Co-Authored-By: Jane Doe <jane@corp.example>",
		"fix: handle generated files in the linter",
		"The report was generated with pandoc.", // mid-line, not a footer
		"Reviewed-by: Maciej Mensfeld <maciej@mensfeld.pl>",
		"",
	}
	for _, line := range kept {
		if matchAny(line) {
			t.Errorf("default patterns must NOT strip %q", line)
		}
	}
}

// Blank pattern lines would match (and with grep -v delete) EVERY message
// line; the renderer must drop them.
func TestRenderAttributionPatternsFile(t *testing.T) {
	got := renderAttributionPatternsFile([]string{"foo", "", "   ", "bar"})
	if got != "foo\nbar\n" {
		t.Errorf("renderAttributionPatternsFile = %q, want %q", got, "foo\nbar\n")
	}
	if renderAttributionPatternsFile(nil) != "" {
		t.Error("nil patterns should render empty")
	}
}

func TestEffectiveAttributionPatterns(t *testing.T) {
	if got := effectiveAttributionPatterns(nil); len(got) != len(DefaultAttributionPatterns) {
		t.Errorf("nil config should yield the defaults, got %v", got)
	}
	custom := []string{"^X-Custom:"}
	if got := effectiveAttributionPatterns(custom); len(got) != 1 || got[0] != "^X-Custom:" {
		t.Errorf("configured patterns must replace the defaults wholesale, got %v", got)
	}
}

// The hook scripts must delegate via --git-dir (NOT --git-path hooks, which
// resolves back through core.hooksPath to this very directory and recurses)
// and the commit-msg script must never be able to reject a commit.
func TestGitHookScripts(t *testing.T) {
	for name, script := range map[string]string{
		"commit-msg": gitCommitMsgHookScript,
		"delegate":   gitDelegateHookScript,
	} {
		if !strings.HasPrefix(script, "#!/bin/sh\n") {
			t.Errorf("%s: missing shebang", name)
		}
		if !strings.Contains(script, "git rev-parse --git-dir") {
			t.Errorf("%s: must delegate via --git-dir", name)
		}
		if strings.Contains(script, "--git-path") {
			t.Errorf("%s: --git-path hooks would recurse through core.hooksPath", name)
		}
		if !strings.Contains(script, "exit 0") {
			t.Errorf("%s: must exit 0 when no repo hook exists (strip-don't-reject)", name)
		}
	}
	if !strings.Contains(gitCommitMsgHookScript, gitAttributionPatternsPath) {
		t.Error("commit-msg script must read the patterns file")
	}
}

func TestSetupGitAttributionHook(t *testing.T) {
	rec := &managedSettingsRecorder{}
	// strip on, identity NOT locked: post-commit stays a delegation symlink.
	SetupGitHooks(rec, "/home/code", GitIdentity{}, true, nil, false, true, func(string) {})

	// Three root-owned files: the two scripts (0755) and the pattern file (0644).
	wantModes := map[string]string{
		GitHooksDir + "/commit-msg": "0755",
		GitHooksDir + "/delegate":   "0755",
		gitAttributionPatternsPath:  "0644",
	}
	if len(rec.creates) != len(wantModes) {
		t.Fatalf("expected %d file writes, got %v", len(wantModes), rec.creates)
	}
	for _, c := range rec.creates {
		mode, ok := wantModes[c.path]
		if !ok {
			t.Errorf("unexpected file written: %s", c.path)
			continue
		}
		if c.mode != mode || c.uid != 0 || c.gid != 0 {
			t.Errorf("%s: mode/owner = %s/%d:%d, want %s/0:0", c.path, c.mode, c.uid, c.gid, mode)
		}
	}

	joined := strings.Join(rec.commands, "\n")
	for _, want := range []string{
		"mkdir -p " + GitHooksDir,
		"ln -sf delegate " + GitHooksDir + "/pre-commit",
		"ln -sf delegate " + GitHooksDir + "/pre-push",
		"git config --global core.hooksPath",
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("expected an exec containing %q, got:\n%s", want, joined)
		}
	}
	// commit-msg must NOT be a delegation symlink — it is the strip script.
	if strings.Contains(joined, "ln -sf delegate "+GitHooksDir+"/commit-msg") {
		t.Error("commit-msg must be the strip script, not a delegation symlink")
	}
	// Identity not locked: post-commit is a delegation symlink (reset first).
	if !strings.Contains(joined, "ln -sf delegate "+GitHooksDir+"/post-commit") {
		t.Error("post-commit must be a delegation symlink when identity is not locked")
	}
}

// With identity locking on (and strip off), post-commit is a REAL root-owned
// re-stamp script — not a symlink — and the strip artifacts are absent.
func TestSetupGitHooks_IdentityLock(t *testing.T) {
	rec := &managedSettingsRecorder{}
	id := GitIdentity{Name: testBotName, Email: testBotEmail}
	SetupGitHooks(rec, "/home/code", id, false, nil, true, true, func(string) {})

	var post *createWithOwnerCall
	for i := range rec.creates {
		switch rec.creates[i].path {
		case GitHooksDir + "/post-commit":
			post = &rec.creates[i]
		case GitHooksDir + "/commit-msg", gitAttributionPatternsPath:
			t.Errorf("strip is off — %s must not be written", rec.creates[i].path)
		}
	}
	if post == nil {
		t.Fatal("post-commit re-stamp file was not written under identity lock")
	}
	if post.uid != 0 || post.gid != 0 || post.mode != "0755" {
		t.Errorf("post-commit owner/mode = %d:%d/%s, want 0:0/0755", post.uid, post.gid, post.mode)
	}
	// The baked identity + all the correctness guards must be present.
	for _, want := range []string{
		id.Email, id.Name,
		"COI_RESTAMP_ACTIVE",
		"--reset-author",
		"--no-verify",
		"--allow-empty", // empty commits must be re-stampable too (amend refuses otherwise)
		"git rev-parse --git-dir",
		"CHERRY_PICK_HEAD",
	} {
		if !strings.Contains(post.content, want) {
			t.Errorf("post-commit script missing %q", want)
		}
	}
	if strings.Contains(post.content, "--git-path") {
		t.Error("post-commit must use --git-dir, not --git-path (recursion)")
	}
	joined := strings.Join(rec.commands, "\n")
	if !strings.Contains(joined, "rm -f "+GitHooksDir+"/post-commit") {
		t.Error("must reset post-commit before writing the re-stamp file")
	}
	if strings.Contains(joined, "ln -sf delegate "+GitHooksDir+"/post-commit") {
		t.Error("post-commit must be the re-stamp file, not a delegation symlink, when locking")
	}
}

// renderPostCommitRestampScript must single-quote-escape the baked identity so a
// name containing a quote can't break out of the assignment.
func TestRenderPostCommitRestampScript_Escaping(t *testing.T) {
	s := renderPostCommitRestampScript(GitIdentity{Name: "O'Brien", Email: "o@x"})
	if !strings.Contains(s, `LOCK_NAME='O'"'"'Brien'`) {
		t.Errorf("identity not safely single-quote-escaped:\n%s", s)
	}
	if !strings.Contains(s, "LOCK_EMAIL='o@x'") {
		t.Errorf("email not baked:\n%s", s)
	}
}

// With [git] readonly the mounted gitconfig carries core.hooksPath, so the
// live config write must be skipped (it would fail against the read-only
// mount and log a spurious warning).
func TestSetupGitAttributionHookSkipsConfigWhenReadonly(t *testing.T) {
	rec := &managedSettingsRecorder{}
	SetupGitHooks(rec, "/home/code", GitIdentity{}, true, nil, false, false, func(string) {})
	for _, cmd := range rec.commands {
		if strings.Contains(cmd, "core.hooksPath") {
			t.Errorf("setHooksPath=false must not write git config, got %q", cmd)
		}
	}
}

func TestRemoveGitAttributionHookConfig(t *testing.T) {
	rec := &managedSettingsRecorder{}
	RemoveGitAttributionHookConfig(rec, "/home/code")
	if len(rec.commands) != 1 || !strings.Contains(rec.commands[0], "--unset core.hooksPath") {
		t.Errorf("expected one unset command, got %v", rec.commands)
	}
}

// The composed managed-settings policy must include exactly the enabled parts.
func TestRenderClaudeManagedSettings(t *testing.T) {
	cases := []struct {
		suppress, strip               bool
		wantAuto, wantCoAuthor, empty bool
	}{
		{true, true, true, true, false},
		{true, false, true, false, false},
		{false, true, false, true, false},
		{false, false, false, false, true},
	}
	for _, c := range cases {
		got := renderClaudeManagedSettings(c.suppress, c.strip)
		if c.empty {
			if got != "" {
				t.Errorf("suppress=%v strip=%v: want empty, got %q", c.suppress, c.strip, got)
			}
			continue
		}
		if strings.Contains(got, "disableAutoMode") != c.wantAuto {
			t.Errorf("suppress=%v strip=%v: disableAutoMode presence wrong: %q", c.suppress, c.strip, got)
		}
		if strings.Contains(got, `"includeCoAuthoredBy": false`) != c.wantCoAuthor {
			t.Errorf("suppress=%v strip=%v: includeCoAuthoredBy presence wrong: %q", c.suppress, c.strip, got)
		}
	}
}
